version: '2.4'
services:
  data-collection:
    build:
      context: ./data-collection
      dockerfile: Dockerfile
    volumes:
      - ./data-collection:/app/src
    command: go run main.go
    depends_on:
      - detection-algos
  detection-algos:
    build:
      context: ./detection-algos
      dockerfile: Dockerfile
    volumes:
      - ./detection-algos:/app/src
    ports:
      - '50051:50051'
    command: go run main.go
    depends_on:
      - trade-service
    mem_limit: 8192m
    cpus: 4.0
  trade-service:
    build:
      context: ./trade-service
      dockerfile: Dockerfile
    env_file:
      - ./trade-service/.env
    volumes:
      - ./trade-service:/app/src
    ports:
      - '50052:50052'
    command: go run main.go
